using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RTSS_time_reader.RTSS_interop
{
    using DWORD = System.UInt32;

    [Flags]
    public enum  VideoCaptureFlags:DWORD
    {
        None                   = 0,
        RequestCaptureStart    = VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_START,
        RequestCaptureProgress = VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_PROGRESS,
        RequestCaptureStop     = VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_STOP,
        RequestCaptureOSD      = VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_OSD,

        INTERNAL_RESIZE = VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_INTERNAL_RESIZE,
        MASK = (VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_START | VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_PROGRESS | VIDEOCAPTUREFLAGS.VIDEOCAPTUREFLAG_REQUEST_CAPTURE_STOP),
    };
}
